### ISSUE TITLE
[Marker.io] About Us Gallery -Mobile

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#116]
[![Screenshot_2023-08-31_08-04-59.png](https://mrkr.io/s/64f049aacc13b59ce3049352/2)](https://mrkr.io/s/64f049aacc13b59ce3049352/0)

Gallery is moving way too fast on mobile. They a both at different speeds with the bottom one faster than the top. 

---

**Reported by:** Deanna Szczygiel (deanna.szczygiel@coatesgroup.com) - [Contact via Marker.io](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/about-us](https://new.coatesgroup.com/about-us)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 16.0</td></tr><tr><td><strong>Screen Size</strong></td><td>414 x 896</td></tr><tr><td><strong>OS</strong></td><td>iOS 16.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>414 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by KirstyBarnet** [comment]
@mikemartin closing this issue as it's the same as issue as what I raised and therefore duplicated.

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64f049aacc13b59ce3049355_e30000dca20065bd) - This issue was marked as **✅ Resolved** in Marker.io
