### ISSUE TITLE
[Marker.io] tag

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#121]
[![Screenshot_2023-08-31_19-54-28.png](https://mrkr.io/s/64f0eff4a31a9b6df047df97/2)](https://mrkr.io/s/64f0eff4a31a9b6df047df97/0)

should be Toronto

---

**Reported by:** Emily Loebig (emily.loebig@coatesgroup.com) - [Contact via Marker.io](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/careers/our-people](https://new.coatesgroup.com/careers/our-people)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 116.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.4.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1745 x 853</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.100000023841858x</td></tr></table>

**Comment by KirstyBarnet** [comment]
@mikemartin closing this issue as I've fixed in the people collection.

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64f0eff4a31a9b6df047df9a_9c06364d7dcc1470) - This issue was marked as **✅ Resolved** in Marker.io
