### ISSUE TITLE
[Marker.io] ODMB page

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#128]
[![Screenshot_2023-09-01_01-06-18.png](https://mrkr.io/s/64f139096cd596eeb871278f/2)](https://mrkr.io/s/64f139096cd596eeb871278f/0)

this links to the IDMB page

---

**Reported by:** Emily Loebig (emily.loebig@coatesgroup.com) - [Contact via Marker.io](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/case-studies/mcdonalds-anz-digital-signage-for-order-accuracy](https://new.coatesgroup.com/case-studies/mcdonalds-anz-digital-signage-for-order-accuracy)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 116.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.4.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>2133 x 1042</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by KirstyBarnet** [comment]
@mikemartin closing this issue as it's already captured in a previous issue raised in a ticket by Anushka and therefore a duplicate.

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64f139096cd596eeb8712792_0410712ec5ee3a59) - This issue was marked as **✅ Resolved** in Marker.io
