### ISSUE TITLE
[Test Case] Can view In Restaurant products

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#79]
On the In Restaurant experiences page, use the product slider to view all 5 products.

**Test steps**
1. Go to [In Restaurant](https://new.coatesgroup.com/what-we-do/in-restaurant-digital-solutions)
2. Scroll down to 'Digital Solutions to Power Your Customer Journey'
3. Mobile: Click the blue arrow to view all 5 products / Desktop: All 5 products should be in view. 

**Expected result**
The product image should scroll into view.

**Comment by nushka2023** [comment]
@mikemartin  just flagging that i think there is an error in this test case as i dont think it makes sense for the in restaurant page? there is not blue arrow for this page to view all 5 products -this is only for the drive thru page.

**Comment by mikemartin** [comment]
@nushka2023 I've adjusted the test case description. The blue arrows are only shown on mobile, and on desktop all products are already in view.
