### ISSUE TITLE
[Marker.io] Homepage video doesn’t play 

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#93]
[![Screenshot_2023-08-30_03-20-53.png](https://mrkr.io/s/64eeb594a1d6ab587e23335e/2)](https://mrkr.io/s/64eeb594a1d6ab587e23335e/0)

I press on the button but nothing happens

---

**Reported by:** CC (cecile@digitalbohemian.com.au) - [Contact via Marker.io](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/](https://new.coatesgroup.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 116.0.5845.118</td></tr><tr><td><strong>Screen Size</strong></td><td>414 x 896</td></tr><tr><td><strong>OS</strong></td><td>iOS 16.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>414 x 720</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by mikemartin** [comment]
@cecile-digitalbohemian Can you confirm if you had low-power mode turned on?

**Comment by mikemartin** [comment]
Turns out if the phone is in low-power mode, videos will not autoplay. The user must click on the Play button to watch the video.

**Comment by cecile-digitalbohemian** [comment]
Yes, I've got it always on.

But, it wasn't a question of autoplay, it was that the button wasn't
functioning.
Many thanks,

Cécile Caminade

Founder

DIGITAL BOHEMIAN <https://www.digitalbohemian.com.au/>
0401 872 481 <0401872481>
***@***.***

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64eeb594a1d6ab587e233361_bafa7c86b725a3a6) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by mikemartin** [comment]
@cecile-digitalbohemian The play button functions now. Can you confirm?

**Comment by cecile-digitalbohemian** [comment]
Confirmed!
Many thanks,

Cécile Caminade

Founder

DIGITAL BOHEMIAN <https://www.digitalbohemian.com.au/>
0401 872 481 <0401872481>
***@***.***
