### ISSUE TITLE
[Marker.io] Goes to the wrong page 

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#95]
[![Screenshot_2023-08-30_03-24-25.png](https://mrkr.io/s/64eeb668ef015e48b66050e7/2)](https://mrkr.io/s/64eeb668ef015e48b66050e7/0)

Should be going to software page

---

**Reported by:** CC (cecile@digitalbohemian.com.au) - [Contact via Marker.io](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/what-we-do/in-restaurant-digital-solutions](https://new.coatesgroup.com/what-we-do/in-restaurant-digital-solutions)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 116.0.5845.118</td></tr><tr><td><strong>Screen Size</strong></td><td>414 x 896</td></tr><tr><td><strong>OS</strong></td><td>iOS 16.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>414 x 828</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by mikemartin** [comment]
@KirstyBarnet I couldn't replicate this. Perhaps it's already been fixed?

**Comment by KirstyBarnet** [comment]
@mikemartin agreed. It's working fine on two different browsers for me. I will close this one.

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64eeb668ef015e48b66050ea_f259af73c2975d89) - This issue was marked as **✅ Resolved** in Marker.io
