### ISSUE TITLE
[Marker.io] SLT Member

### ISSUE THREAD

**Issue by mikemartin** [mikemartin/coatesgroup#97]
[![Screenshot_2023-08-30_04-02-22.png](https://mrkr.io/s/64eebf4dbce38e7bd85e8f3c/2)](https://mrkr.io/s/64eebf4dbce38e7bd85e8f3c/0)

Jeffery Steres is missing from the SLT Page

---

**Reported by:** Rex (rex.abergas@coatesgroup.com) - [Contact via Marker.io](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852?advanced=1&comments=1)

**Source URL:** [https://new.coatesgroup.com/about-us](https://new.coatesgroup.com/about-us)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852?advanced=1)

**Console:** [⚠️  3 warnings ](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 116.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 938</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by KirstyBarnet** [comment]
@mikemartin I added Jeffrey Steres to the SLT page this afternoon so I will close this issue.

**Comment by mikemartin** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/64eebf4dbce38e7bd85e8f3f_55b6818882d89852) - This issue was marked as **✅ Resolved** in Marker.io
